name: kovaii_fine_coat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.3  
  printing: ^5.14.2
  google_fonts: ^6.2.1
  dropdown_search: ^6.0.2
  flutter_svg: ^2.0.17
  csv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/csv/
    - assets/icons/
